server:
  port: 8001

#数据源配置
spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/my-chat?characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 12345678


#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: del
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: t_
  configuration:
    map-underscore-to-camel-case: true

#dubbo配置

